language: php

php:
  - '7.1'
  - '7.2snapshot'
  - '7.3snapshot'

matrix:
  allow_failures:
    - php: '7.3snapshot'
    - php: nightly

before_script:
  - composer install --no-interaction
  - npm install jsonlint -g

script:
  - find app -name "*.php" | xargs -n 1 php -l

cache:
  directories:
  - "$HOME/.composer/cache"
